### ISSUE TITLE
Nouveaux avions.

### ISSUE THREAD

**Issue by duprefm** [GeneralDeGaulle/i_fly_bernard#2]
Bonjour,

ce serait sympathique aussi de suivre les déplacements de nos dirigeants politiques.
Est il possible pour n’importe qui d’ajouter des avions ?

**Comment by GeneralDeGaulle** [comment]
Bonjour et merci pour ton message.

Tu as déjà le compte [](https://twitter.com/CotamFleet) qui fait ce travail pour les avions du gouvernement.
Pour ta seconde question, je peux rajouter des avions que l'on me propose mais pour l'instant, je vise principalement les milliardaires français. Et j'ai ajouté ce que j'ai trouvé. Si tu as des propositions, je suis preneur !

**Comment by duprefm** [comment]
Bonjour,

	Quel est ce compte ?
Par avance merci,
Fabrice

**Comment by duprefm** [comment]
Trouve COTAM Fleet

**Comment by duprefm** [comment]
Bonjour,

J’ai fait un fork de vôtre code.
Je m’attaque aux 7 avions de la flotte présidentielle.

Fabrice

Le jeu. 11 août 2022 à 09:51, GeneralDeGaulle ***@***.***> a
écrit :

**Comment by dranreb38** [comment]
Idem .....

**Comment by GeneralDeGaulle** [comment]
Oui pas de problème !
Pour ajouter des avions, ils suffit de modifier le fichier "avions.csv"

**Comment by duprefm** [comment]
J’ai aussi eut des path à modifier, je suis sur Linux

Le jeu. 11 août 2022 à 14:05, GeneralDeGaulle ***@***.***> a
écrit :

**Comment by duprefm** [comment]
Je vous dis ça à partir de dimanche, là nous sommes en camping sans
ordinateur. je fais une branche à partir de votre repos.

Le jeu. 11 août 2022 à 16:02, GeneralDeGaulle ***@***.***> a
écrit :
